BEGIN;

-- Source-backed research, not adopted policy. The source locator and the
-- applicability trigger must be reviewed against the live authority before
-- any rule is promoted into a pinned policy version.
WITH researched AS (
  SELECT * FROM jsonb_to_recordset($rules$[
    {"code":"US-01","title":"Bank customer identification at account opening","jurisdiction":"US","rule_kind":"operator_cdd","source_authority":"U.S. Treasury / eCFR","source_url":"https://www.ecfr.gov/current/title-31/subtitle-B/chapter-X/part-1020/subpart-B/section-1020.220","source_locator":"31 CFR 1020.220(a)(2)","rule_summary":"A covered bank's customer identification program obtains identifying information and verifies the identity of a legal entity opening an account.","legal_trigger":"The onboarding operator is a covered U.S. bank and opens a covered account for the applicant.","evidence_to_review":"Legal name, physical business address, identification number and the bank's chosen verification records, which may include formation documents.","exceptions_to_review":"Account and customer definitions; existing-customer exclusions and risk-based verification methods.","provider_roles":["bank"],"payment_activities":[],"operating_jurisdictions":[]},
    {"code":"US-02","title":"U.S. legal entity beneficial ownership CDD","jurisdiction":"US","rule_kind":"operator_cdd","source_authority":"FinCEN / eCFR","source_url":"https://www.ecfr.gov/current/title-31/subtitle-B/chapter-X/part-1010/subpart-B/section-1010.230","source_locator":"31 CFR 1010.230(b)-(d); FinCEN February 2026 relief","rule_summary":"A covered financial institution identifies and verifies beneficial owners of a covered legal entity customer under the CDD rule.","legal_trigger":"A covered institution opens a covered account for a covered legal entity, subject to current FinCEN relief.","evidence_to_review":"Ownership chain, natural persons at the rule's ownership threshold, one control person, and the institution's identity-verification record.","exceptions_to_review":"Excluded entity types, account types and February 2026 relief from repeat collection; verify the current FinCEN order before activation.","provider_roles":["bank"],"payment_activities":[],"operating_jurisdictions":[]},
    {"code":"US-03","title":"U.S. money services business program and registration","jurisdiction":"US","rule_kind":"applicant_license","source_authority":"FinCEN","source_url":"https://www.fincen.gov/resources/money-services-business-msb-registration","source_locator":"MSB registration guidance; 31 CFR 1022.210 for AML program","rule_summary":"A business carrying on federally defined MSB activity may have FinCEN registration and AML-program obligations.","legal_trigger":"The applicant itself conducts a covered MSB activity with a U.S. nexus.","evidence_to_review":"Actual services and fund flow, FinCEN registration status and relevant AML-program information.","exceptions_to_review":"Agent status, exemption and activity definitions; a business-type label alone is insufficient.","provider_roles":[],"payment_activities":["receives_or_transmits"],"operating_jurisdictions":["US"]},
    {"code":"US-04","title":"U.S. sanctions compliance framework","jurisdiction":"US","rule_kind":"risk_guidance","source_authority":"OFAC","source_url":"https://ofac.treasury.gov/system/files/126/framework_ofac_cc.pdf","source_locator":"A Framework for OFAC Compliance Commitments","rule_summary":"Organizations subject to U.S. sanctions jurisdiction should design risk-based sanctions controls around their exposure.","legal_trigger":"The operator has a U.S. sanctions nexus; the exact prohibition and screening action depend on the counterparties and transaction.","evidence_to_review":"Identity, ownership, counterparties, products, corridors and investigated sanctions-screening results.","exceptions_to_review":"A possible name match is not a concluded sanctions violation; assess actual control, ownership and transaction facts.","provider_roles":[],"payment_activities":[],"operating_jurisdictions":["US"]},
    {"code":"CA-01","title":"California money transmission license","jurisdiction":"US-CA","rule_kind":"applicant_license","source_authority":"California DFPI","source_url":"https://dfpi.ca.gov/rules-enforcement/laws-and-regulations/opinion-letters-by-law-subject/opinion-letters-archives/ca-money-transmission-act-2013-commissioners-opinion-no-002/","source_locator":"California Money Transmission Act; Financial Code section 2030","rule_summary":"A person engaging in regulated money transmission in California generally needs a license or a valid exception.","legal_trigger":"The applicant itself transmits money in California under the statutory definition.","evidence_to_review":"Fund-flow diagram, California customer/service nexus, license record or documented exemption/authorized-agent basis.","exceptions_to_review":"Statutory exclusions and authorized-delegate arrangements; incorporation in California alone does not establish the trigger.","provider_roles":[],"payment_activities":["receives_or_transmits"],"operating_jurisdictions":["US-CA"]},
    {"code":"DE-01","title":"Delaware money transmission license","jurisdiction":"US-DE","rule_kind":"applicant_license","source_authority":"Delaware Code","source_url":"https://delcode.delaware.gov/title5/c023/sc02/index.html","source_locator":"5 Del. C. section 2304","rule_summary":"Delaware restricts unlicensed money transmission involving a person located in the state, subject to statutory exceptions.","legal_trigger":"The applicant itself engages in covered money transmission involving Delaware.","evidence_to_review":"Transaction and customer locations, fund flow, state license or documented delegate/exemption basis.","exceptions_to_review":"Chapter 23 definitions, exclusions and authorized-delegate status.","provider_roles":[],"payment_activities":["receives_or_transmits"],"operating_jurisdictions":["US-DE"]},
    {"code":"NY-01","title":"New York money transmitter license","jurisdiction":"US-NY","rule_kind":"applicant_license","source_authority":"New York DFS","source_url":"https://www.dfs.ny.gov/apps_and_licensing/money_transmitters","source_locator":"Money transmitter licensing guidance","rule_summary":"Covered receipt or transmission of money in New York may require a DFS money transmitter license.","legal_trigger":"The applicant itself conducts activity within the New York licensing perimeter.","evidence_to_review":"New York nexus, transaction contracts and fund flow, DFS license or reason an exemption/agency arrangement applies.","exceptions_to_review":"Specific New York nexus and agency/exemption analysis; formation location alone is insufficient.","provider_roles":[],"payment_activities":["receives_or_transmits"],"operating_jurisdictions":["US-NY"]},
    {"code":"TX-01","title":"Texas money services licensing","jurisdiction":"US-TX","rule_kind":"applicant_license","source_authority":"Texas Department of Banking","source_url":"https://dob.texas.gov/money-services-businesses","source_locator":"Texas Finance Code Chapter 152; Department of Banking guidance","rule_summary":"Covered money transmission involving Texas can require a Chapter 152 license.","legal_trigger":"The applicant itself performs covered money transmission involving Texas.","evidence_to_review":"Texas customer/service nexus, fund flow, license or authorized-delegate/exemption evidence.","exceptions_to_review":"Current Chapter 152 definitions and exceptions; do not apply superseded Chapter 151.","provider_roles":[],"payment_activities":["receives_or_transmits"],"operating_jurisdictions":["US-TX"]},
    {"code":"WA-01","title":"Washington money transmitter license","jurisdiction":"US-WA","rule_kind":"applicant_license","source_authority":"Washington Legislature","source_url":"https://app.leg.wa.gov/rcw/default.aspx?cite=19.230&full=true","source_locator":"RCW 19.230.030 and definitions/exclusions","rule_summary":"Washington restricts money transmission without a license, authorized-delegate basis or statutory exclusion.","legal_trigger":"The applicant itself conducts covered money transmission with a Washington nexus.","evidence_to_review":"Washington customer/service locations, fund flow, DFI license or documented delegate/exclusion basis.","exceptions_to_review":"Current statutory definitions, exemptions and authorized-delegate conditions.","provider_roles":[],"payment_activities":["receives_or_transmits"],"operating_jurisdictions":["US-WA"]},
    {"code":"GB-01","title":"UK customer due diligence for a business relationship","jurisdiction":"GB","rule_kind":"operator_cdd","source_authority":"UK legislation","source_url":"https://www.legislation.gov.uk/uksi/2017/692/part/3/chapter/2","source_locator":"Money Laundering Regulations 2017, regulations 27-28","rule_summary":"A relevant person applies CDD when establishing a business relationship and identifies and verifies the customer and beneficial owner as required.","legal_trigger":"The onboarding operator is a relevant person under the regulations and a CDD trigger occurs.","evidence_to_review":"Legal entity identity, ownership/control, acting-person authority and purpose/intended nature of relationship.","exceptions_to_review":"Relevant-person status, simplified/enhanced measures and reliance; confirm current amended regulation text.","provider_roles":["bank","payment_institution","money_transmitter"],"payment_activities":[],"operating_jurisdictions":[]},
    {"code":"GB-02","title":"UK regulated payment-services perimeter","jurisdiction":"GB","rule_kind":"applicant_license","source_authority":"UK Financial Conduct Authority","source_url":"https://www.fca.org.uk/firms/payment-services-regulations-e-money-regulations","source_locator":"Payment Services Regulations and E-Money Regulations overview","rule_summary":"A business providing regulated payment services in the UK may need FCA authorization or registration in the correct category.","legal_trigger":"The applicant itself provides a regulated payment service as a business in the UK.","evidence_to_review":"Service contracts, UK activity/fund flow, FCA register entry or documented permitted-provider/exclusion basis.","exceptions_to_review":"Regulated-service definition, permitted provider types and statutory exclusions; partner use alone does not decide the perimeter.","provider_roles":[],"payment_activities":["facilitates","receives_or_transmits"],"operating_jurisdictions":["GB"]},
    {"code":"CA-FED-01","title":"Canada entity beneficial-ownership information","jurisdiction":"CA","rule_kind":"operator_cdd","source_authority":"FINTRAC","source_url":"https://fintrac-canafe.canada.ca/guidance-directives/client-clientele/bor-eng","source_locator":"Beneficial ownership requirements for reporting entities","rule_summary":"When a reporting entity must verify an entity's identity, it obtains and confirms beneficial-ownership information under FINTRAC guidance.","legal_trigger":"The onboarding operator is an in-scope Canadian reporting entity and an entity-verification trigger occurs.","evidence_to_review":"Entity identity, ownership/control structure and natural persons meeting the current threshold.","exceptions_to_review":"Sector-specific triggers, exceptions and methods; verify the current FINTRAC guidance before activation.","provider_roles":["bank","payment_institution","money_transmitter"],"payment_activities":[],"operating_jurisdictions":[]},
    {"code":"CA-FED-02","title":"Canada MSB registration","jurisdiction":"CA","rule_kind":"applicant_license","source_authority":"FINTRAC","source_url":"https://fintrac-canafe.canada.ca/msb-esm/register-inscrire/reg-ins-eng","source_locator":"Money services businesses and foreign MSBs","rule_summary":"A business providing defined money-services activities in Canada, or a covered foreign MSB directed at Canada, may have FINTRAC registration duties.","legal_trigger":"The applicant itself performs an in-scope MSB service with the required Canadian nexus.","evidence_to_review":"Exact service, Canadian customer nexus, FINTRAC registration or documented reason registration does not apply.","exceptions_to_review":"Foreign-MSB test, agent status and current activity definitions.","provider_roles":[],"payment_activities":["receives_or_transmits"],"operating_jurisdictions":["CA"]},
    {"code":"CA-FED-03","title":"Canada retail payment service provider registration","jurisdiction":"CA","rule_kind":"applicant_license","source_authority":"Bank of Canada","source_url":"https://www.bankofcanada.ca/2026/06/criteria-for-registering-payment-service-providers/","source_locator":"RPAA registration criteria, updated June 29 2026","rule_summary":"A PSP meeting the RPAA payment-function, retail-activity and geographic tests must register unless excluded.","legal_trigger":"The applicant performs a non-incidental payment function related to an EFT and has the required Canadian nexus.","evidence_to_review":"Function-by-function service map, EFT flow, customer geography and Bank of Canada registry result.","exceptions_to_review":"Incidental activity, excluded entities/activities and agent or mandatary status.","provider_roles":[],"payment_activities":["facilitates","receives_or_transmits"],"operating_jurisdictions":["CA"]},
    {"code":"SG-01","title":"Singapore specified payment-service CDD","jurisdiction":"SG","rule_kind":"operator_cdd","source_authority":"Monetary Authority of Singapore","source_url":"https://www.mas.gov.sg/regulation/notices/psn01-aml-cft-notice---specified-payment-services","source_locator":"MAS Notice PSN01, current notice and amendments","rule_summary":"An in-scope payment-service licensee applies the Notice's customer due-diligence measures for specified payment services.","legal_trigger":"The onboarding operator is an in-scope Singapore licensee providing a specified payment service.","evidence_to_review":"Customer and representative identity, legal-person ownership/control, beneficial owners and the applicable transaction/service category.","exceptions_to_review":"Notice scope, transaction thresholds, exemptions and 2025 amendments; verify exact paragraphs before activation.","provider_roles":["payment_institution"],"payment_activities":[],"operating_jurisdictions":[]},
    {"code":"SG-02","title":"Singapore payment-services licensing","jurisdiction":"SG","rule_kind":"applicant_license","source_authority":"Singapore Statutes Online","source_url":"https://sso.agc.gov.sg/Act/PSA2019?ProvIds=pr5-&ViewType=Advance&WiAl=1","source_locator":"Payment Services Act 2019, section 5","rule_summary":"A person carrying on a business of providing a payment service in Singapore generally needs the applicable licence unless exempt.","legal_trigger":"The applicant itself provides a regulated payment service in Singapore.","evidence_to_review":"Exact statutory service, Singapore nexus, MAS register status or exemption basis and fund flow.","exceptions_to_review":"Exempt persons and services; marketplace or software labels alone are inconclusive.","provider_roles":[],"payment_activities":["facilitates","receives_or_transmits"],"operating_jurisdictions":["SG"]},
    {"code":"AU-01","title":"Australia initial customer due diligence","jurisdiction":"AU","rule_kind":"operator_cdd","source_authority":"AUSTRAC","source_url":"https://www.austrac.gov.au/industry-and-business/obligations-and-guidance/your-amlctf-program/customer-due-diligence/initial-customer-due-diligence/overview-initial-customer-due-diligence","source_locator":"Initial CDD guidance, 2026 reforms","rule_summary":"A reporting entity completes initial CDD before providing a designated service, subject to current timing rules and exceptions.","legal_trigger":"The onboarding operator is an Australian reporting entity about to provide a designated service.","evidence_to_review":"Legal entity and representative identity, ownership/control and the records required by the applicable customer-type guidance.","exceptions_to_review":"Delayed/simplified CDD and transitional arrangements under the 2026 regime.","provider_roles":["bank","payment_institution","money_transmitter"],"payment_activities":[],"operating_jurisdictions":[]},
    {"code":"AU-02","title":"Australia remittance registration","jurisdiction":"AU","rule_kind":"applicant_license","source_authority":"AUSTRAC","source_url":"https://www.austrac.gov.au/new-austrac/register-us/register-us-remittance-or-virtual-asset-service-provider","source_locator":"Register as a remittance service provider","rule_summary":"A business providing a registrable remittance service in Australia must meet AUSTRAC registration requirements.","legal_trigger":"The applicant itself provides a remittance service with the required Australian geographical link.","evidence_to_review":"Actual remittance service, geographic link and AUSTRAC enrolment/registration status.","exceptions_to_review":"Service classification and registration category; requesting cross-border payouts from a provider is insufficient.","provider_roles":[],"payment_activities":["receives_or_transmits"],"operating_jurisdictions":["AU"]},
    {"code":"IE-01","title":"Ireland payment-institution authorisation","jurisdiction":"IE","rule_kind":"applicant_license","source_authority":"Central Bank of Ireland","source_url":"https://www.centralbank.ie/regulation/industry-market-sectors/payment-institutions","source_locator":"Payment Institutions; Payment Services Regulations 2018","rule_summary":"A payment institution generally requires Central Bank authorisation to provide listed payment services in Ireland.","legal_trigger":"The applicant itself provides a listed payment service in Ireland and is not already another permitted PSP or excluded.","evidence_to_review":"Service contracts and fund flow, Irish customer nexus and regulator authorisation/passporting evidence.","exceptions_to_review":"Other permitted PSP categories, exclusions and EU passporting; UK partner status is not EU authorisation.","provider_roles":[],"payment_activities":["facilitates","receives_or_transmits"],"operating_jurisdictions":["IE"]},
    {"code":"DE-BUND-01","title":"Germany payment-services authorisation","jurisdiction":"DE","rule_kind":"applicant_license","source_authority":"German Federal Ministry of Justice","source_url":"https://www.gesetze-im-internet.de/zag_2018/__10.html","source_locator":"Zahlungsdiensteaufsichtsgesetz (ZAG) section 10(1)","rule_summary":"A business providing payment services in Germany may require BaFin authorisation under ZAG section 10.","legal_trigger":"The applicant itself commercially provides a defined payment service in Germany and is not another permitted PSP.","evidence_to_review":"Contracts, service classification, German customer nexus, BaFin register entry or documented permitted-provider basis.","exceptions_to_review":"ZAG section 1 definitions/exclusions, other permitted PSPs and EU passporting; translate and review the official German text.","provider_roles":[],"payment_activities":["facilitates","receives_or_transmits"],"operating_jurisdictions":["DE"]}
  ]$rules$::jsonb) AS x(
    code text, title text, jurisdiction text, rule_kind text,
    source_authority text, source_url text, source_locator text,
    rule_summary text, legal_trigger text, evidence_to_review text,
    exceptions_to_review text, provider_roles text[],
    payment_activities text[], operating_jurisdictions text[]
  )
)
INSERT INTO policy_research_candidates (
  code, title, jurisdiction, rule_kind, source_authority, source_url,
  source_locator, rule_summary, legal_trigger, evidence_to_review,
  exceptions_to_review, provider_roles, payment_activities,
  operating_jurisdictions, researched_on
)
SELECT code, title, jurisdiction, rule_kind, source_authority, source_url,
  source_locator, rule_summary, legal_trigger, evidence_to_review,
  exceptions_to_review, provider_roles, payment_activities,
  operating_jurisdictions, DATE '2026-09-24'
FROM researched
ON CONFLICT (code) DO NOTHING;

DO $$
BEGIN
  IF (SELECT count(*) FROM policy_research_candidates WHERE code IN (
    'US-01','US-02','US-03','US-04','CA-01','DE-01','NY-01','TX-01','WA-01',
    'GB-01','GB-02','CA-FED-01','CA-FED-02','CA-FED-03','SG-01','SG-02',
    'AU-01','AU-02','IE-01','DE-BUND-01'
  )) <> 20 THEN
    RAISE EXCEPTION 'expected all 20 policy research candidates';
  END IF;
END $$;

COMMIT;
